/**
 * Robots.txt Generator
 * Generates crawler instructions for search engines
 */
import { useState } from 'react';
import { Bot, Plus, Trash2, Download, Copy, Check, Info, AlertTriangle, ShieldAlert } from 'lucide-react';
import ToolOutput from '../ToolOutput';

interface RobotsRule {
  userAgent: string;
  allow: string;
  disallow: string;
}

export default function RobotsGenerator() {
  const [rules, setRules] = useState<RobotsRule[]>([
    { userAgent: '*', allow: '/', disallow: '/admin/' }
  ]);
  const [crawlDelay, setCrawlDelay] = useState('');
  const [sitemapUrl, setSitemapUrl] = useState('');
  const [output, setOutput] = useState('');

  const addRule = () => {
    setRules([...rules, { userAgent: '', allow: '', disallow: '' }]);
  };

  const removeRule = (index: number) => {
    if (rules.length === 1) return;
    const newRules = [...rules];
    newRules.splice(index, 1);
    setRules(newRules);
  };

  const updateRule = (index: number, field: keyof RobotsRule, value: string) => {
    const newRules = [...rules];
    newRules[index][field] = value;
    setRules(newRules);
  };

  const generateRobots = () => {
    let txt = `# Robots.txt generated by VDesignU SEO Tools\n`;
    txt += `# Date: ${new Date().toLocaleDateString()}\n\n`;

    rules.forEach(rule => {
      txt += `User-agent: ${rule.userAgent.trim() || '*'}\n`;
      if (rule.disallow) {
        rule.disallow.split(',').forEach(path => {
          if (path.trim()) txt += `Disallow: ${path.trim()}\n`;
        });
      }
      if (rule.allow) {
        rule.allow.split(',').forEach(path => {
          if (path.trim()) txt += `Allow: ${path.trim()}\n`;
        });
      }
      if (crawlDelay) txt += `Crawl-delay: ${crawlDelay}\n`;
      txt += `\n`;
    });

    if (sitemapUrl) {
      txt += `Sitemap: ${sitemapUrl.trim()}\n`;
    }

    setOutput(txt);
  };

  return (
    <div className="max-w-6xl mx-auto">
      <div className="grid lg:grid-cols-2 gap-12">
        {/* Input Panel */}
        <div className="bg-[var(--bg-card)] border-2 border-[var(--border-subtle)] rounded-[2.5rem] p-10 shadow-2xl relative overflow-hidden">
          <div className="flex items-center justify-between mb-10">
            <div className="flex items-center gap-4">
              <div className="w-14 h-14 rounded-2xl bg-black flex items-center justify-center text-white shadow-xl shadow-black/20">
                <Bot className="w-7 h-7" />
              </div>
              <div>
                <h3 className="text-xl font-black uppercase tracking-tight text-[var(--text-primary)]">Robots Config</h3>
                <p className="text-xs font-bold text-[var(--text-muted)] uppercase tracking-widest">Crawler Governance</p>
              </div>
            </div>
            <button 
              onClick={addRule}
              className="flex items-center gap-2 px-4 py-2 bg-black text-white rounded-xl text-xs font-black uppercase tracking-widest hover:bg-[var(--accent-red)] transition-all active:scale-95"
            >
              <Plus className="w-4 h-4" />
              Add User-Agent
            </button>
          </div>

          <div className="space-y-6 mb-10 max-h-[500px] overflow-y-auto pr-2 custom-scrollbar">
            {rules.map((rule, index) => (
              <div key={index} className="bg-[var(--bg-primary)] border-2 border-[var(--border-subtle)] rounded-2xl p-6 relative group transition-all hover:border-[var(--accent-red)]/30">
                <button 
                  onClick={() => removeRule(index)}
                  className="absolute -top-3 -right-3 w-8 h-8 bg-black text-white rounded-full flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity hover:bg-[var(--accent-red)]"
                >
                  <Trash2 className="w-4 h-4" />
                </button>

                <div className="space-y-4">
                   <div>
                      <label className="block text-[10px] font-black uppercase tracking-[0.2em] text-[var(--text-muted)] mb-2">User-Agent</label>
                      <input
                        type="text"
                        value={rule.userAgent}
                        onChange={(e) => updateRule(index, 'userAgent', e.target.value)}
                        placeholder="*"
                        className="w-full px-4 py-3 bg-[var(--bg-card)] border border-[var(--border-subtle)] rounded-xl text-[var(--text-primary)] font-bold focus:border-[var(--accent-red)] focus:outline-none"
                      />
                   </div>
                   <div className="grid grid-cols-2 gap-4">
                      <div>
                        <label className="block text-[10px] font-black uppercase tracking-[0.2em] text-green-500 mb-2">Allow Paths</label>
                        <input
                          type="text"
                          value={rule.allow}
                          onChange={(e) => updateRule(index, 'allow', e.target.value)}
                          placeholder="/"
                          className="w-full px-4 py-3 bg-[var(--bg-card)] border border-[var(--border-subtle)] rounded-xl text-[var(--text-primary)] text-xs focus:border-green-500 focus:outline-none"
                        />
                      </div>
                      <div>
                        <label className="block text-[10px] font-black uppercase tracking-[0.2em] text-red-500 mb-2">Disallow Paths</label>
                        <input
                          type="text"
                          value={rule.disallow}
                          onChange={(e) => updateRule(index, 'disallow', e.target.value)}
                          placeholder="/admin/"
                          className="w-full px-4 py-3 bg-[var(--bg-card)] border border-[var(--border-subtle)] rounded-xl text-[var(--text-primary)] text-xs focus:border-red-500 focus:outline-none"
                        />
                      </div>
                   </div>
                </div>
              </div>
            ))}
          </div>

          <div className="grid grid-cols-2 gap-4 mb-10">
             <div>
                <label className="block text-[10px] font-black uppercase tracking-[0.2em] text-[var(--text-muted)] mb-3">Crawl Delay (Seconds)</label>
                <input
                  type="number"
                  value={crawlDelay}
                  onChange={(e) => setCrawlDelay(e.target.value)}
                  placeholder="e.g. 5"
                  className="w-full px-4 py-3 bg-[var(--bg-primary)] border border-[var(--border-subtle)] rounded-xl text-[var(--text-primary)] font-bold focus:border-[var(--accent-red)] focus:outline-none"
                />
             </div>
             <div>
                <label className="block text-[10px] font-black uppercase tracking-[0.2em] text-[var(--text-muted)] mb-3">Sitemap XML URL</label>
                <input
                  type="url"
                  value={sitemapUrl}
                  onChange={(e) => setSitemapUrl(e.target.value)}
                  placeholder="https://site.com/sitemap.xml"
                  className="w-full px-4 py-3 bg-[var(--bg-primary)] border border-[var(--border-subtle)] rounded-xl text-[var(--text-primary)] font-bold focus:border-[var(--accent-red)] focus:outline-none"
                />
             </div>
          </div>

          <button
            onClick={generateRobots}
            className="w-full py-6 bg-black text-white font-black italic uppercase tracking-tighter text-2xl rounded-2xl hover:bg-[var(--accent-red)] transition-all active:scale-[0.98] shadow-2xl flex items-center justify-center gap-3 group"
          >
            Generate Robots.txt
            <Bot className="w-6 h-6 group-hover:rotate-12 transition-transform" />
          </button>
        </div>

        {/* Output Panel */}
        <div className="space-y-8">
           <ToolOutput 
             output={output} 
             language="plaintext" 
             title="Generated Robots.txt"
           />

           <div className="bg-amber-500/10 border-2 border-amber-500/20 rounded-[2.5rem] p-8">
              <div className="flex items-center gap-3 text-amber-600 mb-4">
                 <ShieldAlert className="w-6 h-6" />
                 <h4 className="text-sm font-black uppercase tracking-widest">Crawler Safety Warning</h4>
              </div>
              <p className="text-xs text-amber-700 font-medium leading-relaxed mb-4">
                 Misconfiguring your robots.txt can accidentally de-index your entire website. Always test your generated code in the <strong>Google Search Console Robots Tester</strong> before deployment.
              </p>
              <ul className="space-y-2 text-[10px] text-amber-800 font-bold uppercase tracking-tight">
                 <li className="flex items-center gap-2">
                    <div className="w-1 h-1 rounded-full bg-amber-600"></div>
                    Do not disallow CSS or JS files (essential for rendering).
                 </li>
                 <li className="flex items-center gap-2">
                    <div className="w-1 h-1 rounded-full bg-amber-600"></div>
                    Ensure the Sitemap URL is absolute (includes https://).
                 </li>
                 <li className="flex items-center gap-2">
                    <div className="w-1 h-1 rounded-full bg-amber-600"></div>
                    Use * for general rules, and specific bots for custom logic.
                 </li>
              </ul>
           </div>
        </div>
      </div>
    </div>
  );
}
