/**
 * UAE VAT Calculator
 * Calculates 5% VAT for UAE transactions with professional reporting
 */
import { useState, useEffect } from 'react';
import { Calculator, ArrowRight, Download, FileSpreadsheet, ExternalLink, ShieldCheck, Info } from 'lucide-react';

export default function UAEVATCalculator() {
  const [amount, setAmount] = useState('');
  const [vatType, setVatType] = useState<'exclusive' | 'inclusive'>('exclusive');
  const [calculated, setCalculated] = useState(false);
  const [animate, setAnimate] = useState(false);

  const VAT_RATE = 0.05; // 5% UAE VAT

  useEffect(() => {
    if (calculated) {
      setAnimate(false);
      const timer = setTimeout(() => setAnimate(true), 50);
      return () => clearTimeout(timer);
    }
  }, [calculated, amount, vatType]);

  const calculate = () => {
    if (!amount || isNaN(parseFloat(amount))) return;
    setCalculated(true);
  };

  const parsedAmount = parseFloat(amount) || 0;
  
  let netAmount: number;
  let vatAmount: number;
  let totalAmount: number;

  if (vatType === 'exclusive') {
    netAmount = parsedAmount;
    vatAmount = parsedAmount * VAT_RATE;
    totalAmount = parsedAmount + vatAmount;
  } else {
    totalAmount = parsedAmount;
    netAmount = parsedAmount / (1 + VAT_RATE);
    vatAmount = totalAmount - netAmount;
  }

  const vatPercentageOfTotal = (vatAmount / totalAmount) * 100;

  const formatCurrency = (value: number) => {
    return new Intl.NumberFormat('en-AE', {
      style: 'currency',
      currency: 'AED',
      minimumFractionDigits: 2
    }).format(value);
  };

  const downloadReceipt = () => {
    const receipt = `
UAE VAT CALCULATION RECEIPT
===========================
Date: ${new Date().toLocaleDateString('en-AE')}
VAT Rate: 5% (Standard)

COMPLIANCE DATA:
---------------------------
Calculation Type: ${vatType === 'exclusive' ? 'Exclusive (VAT added to Net)' : 'Inclusive (VAT extracted from Total)'}
Source Registry: Federal Tax Authority (FTA) UAE

BREAKDOWN:
---------------------------
Net Amount (excl. VAT): ${formatCurrency(netAmount)}
VAT Amount (5%):        ${formatCurrency(vatAmount)}
---------------------------
TOTAL AMOUNT:           ${formatCurrency(totalAmount)}

LEGAL NOTICE:
This calculation is for preliminary informational purposes. 
VDesignU is not a tax advisory firm. For official FTA filings, 
refer to Federal Decree-Law No. (8) of 2017.

Generated by VDesignU SEO Tools Suite
https://vdesignu.com/tools/gcc-compliance/uae-vat-calculator
    `.trim();

    const blob = new Blob([receipt], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `uae-vat-breakdown-${Date.now()}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="max-w-5xl mx-auto">
      <div className="grid lg:grid-cols-12 gap-8 items-start">
        {/* Input Panel */}
        <div className="lg:col-span-5 bg-[var(--bg-card)] border-2 border-[var(--border-subtle)] rounded-[2.5rem] p-10 shadow-2xl shadow-black/5 relative overflow-hidden group">
          <div className="absolute top-0 right-0 w-32 h-32 bg-[var(--accent-red)]/5 rounded-full blur-3xl -mr-16 -mt-16"></div>
          
          <div className="flex items-center gap-4 mb-10 relative z-10">
            <div className="w-14 h-14 rounded-2xl bg-[var(--accent-red)] flex items-center justify-center text-white shadow-xl shadow-red-600/20 group-hover:rotate-6 transition-transform">
              <Calculator className="w-7 h-7" />
            </div>
            <div>
              <h3 className="text-xl font-black uppercase tracking-tight text-[var(--text-primary)] leading-none mb-2">
                VAT Config<span className="text-[var(--accent-yellow)]">.</span>
              </h3>
              <div className="flex items-center gap-1.5 text-xs font-bold text-[var(--text-muted)] uppercase tracking-widest">
                <ShieldCheck className="w-3 h-3 text-[var(--accent-red)]" />
                FTA Compliant (5%)
              </div>
            </div>
          </div>

          {/* Type Toggle */}
          <div className="mb-8 relative z-10">
            <label className="block text-[10px] font-black uppercase tracking-[0.2em] text-[var(--text-muted)] mb-4 ml-1">
              Calculation Logic
            </label>
            <div className="grid grid-cols-2 gap-2 p-1.5 bg-[var(--bg-primary)] rounded-2xl border border-[var(--border-subtle)]">
              <button
                onClick={() => { setVatType('exclusive'); setCalculated(false); }}
                className={`py-4 px-4 rounded-xl text-xs font-black uppercase tracking-widest transition-all ${
                  vatType === 'exclusive'
                    ? 'bg-[var(--accent-red)] text-white shadow-lg active:scale-95'
                    : 'text-[var(--text-secondary)] hover:text-[var(--text-primary)] hover:bg-[var(--bg-card)]'
                }`}
              >
                Add VAT
              </button>
              <button
                onClick={() => { setVatType('inclusive'); setCalculated(false); }}
                className={`py-4 px-4 rounded-xl text-xs font-black uppercase tracking-widest transition-all ${
                  vatType === 'inclusive'
                    ? 'bg-[var(--accent-red)] text-white shadow-lg active:scale-95'
                    : 'text-[var(--text-secondary)] hover:text-[var(--text-primary)] hover:bg-[var(--bg-card)]'
                }`}
              >
                Extract VAT
              </button>
            </div>
          </div>

          {/* Amount Input */}
          <div className="mb-10 relative z-10">
            <label className="block text-[10px] font-black uppercase tracking-[0.2em] text-[var(--text-muted)] mb-3 ml-1">
              Base Amount (AED)
            </label>
            <div className="relative group/input">
              <div className="absolute left-6 top-1/2 -translate-y-1/2 text-[var(--text-muted)] font-black italic text-lg opacity-40 group-focus-within/input:opacity-100 group-focus-within/input:text-[var(--accent-red)] transition-all">
                AED
              </div>
              <input
                type="number"
                value={amount}
                onChange={(e) => { setAmount(e.target.value); setCalculated(false); }}
                placeholder="0.00"
                className="w-full pl-20 pr-6 py-6 bg-[var(--bg-primary)] border-2 border-[var(--border-subtle)] rounded-2xl text-4xl font-black italic text-[var(--text-primary)] placeholder-[var(--text-muted)] focus:border-[var(--accent-red)] focus:outline-none transition-all shadow-inner"
              />
            </div>
          </div>

          <button
            onClick={calculate}
            disabled={!amount || parseFloat(amount) <= 0}
            className="w-full py-6 bg-[var(--accent-red)] text-white font-black italic uppercase tracking-tighter text-2xl rounded-2xl hover:bg-black transition-all active:scale-[0.98] shadow-2xl shadow-red-600/20 disabled:opacity-30 disabled:grayscale flex items-center justify-center gap-3"
          >
            Calculate Now
            <ArrowRight className="w-6 h-6" />
          </button>
        </div>

        {/* Results Panel */}
        <div className="lg:col-span-7 space-y-8">
          <div className={`bg-[var(--bg-card)] border-2 ${calculated ? 'border-[var(--accent-red)]' : 'border-[var(--border-subtle)]'} rounded-[2.5rem] p-10 shadow-2xl transition-all relative overflow-hidden h-full flex flex-col`}>
             <div className="flex items-center justify-between mb-10">
                <h3 className="text-xl font-black uppercase tracking-tight text-[var(--text-primary)]">
                  Breakdown Analysis<span className="text-[var(--accent-yellow)]">.</span>
                </h3>
                {calculated && (
                  <span className="px-3 py-1 bg-[var(--accent-red)]/10 text-[var(--accent-red)] text-[10px] font-black uppercase tracking-widest rounded-lg">
                    Processed
                  </span>
                )}
             </div>

            {calculated && parsedAmount > 0 ? (
              <div className="flex-grow flex flex-col justify-between">
                <div className="grid md:grid-cols-2 gap-12 items-center mb-12">
                   {/* Mini Chart */}
                   <div className="relative w-48 h-48 mx-auto">
                      <svg className="w-full h-full rotate-[-90deg]" viewBox="0 0 100 100">
                         {/* Total circle background */}
                         <circle cx="50" cy="50" r="45" fill="none" stroke="currentColor" strokeWidth="10" className="text-[var(--border-subtle)]" />
                         {/* VAT segment */}
                         <circle 
                            cx="50" 
                            cy="50" 
                            r="45" 
                            fill="none" 
                            stroke="var(--accent-red)" 
                            strokeWidth="10" 
                            strokeDasharray={`${vatPercentageOfTotal * 2.82} 282`}
                            strokeLinecap="round"
                            className={`transition-all duration-1000 ease-out ${animate ? 'opacity-100' : 'opacity-0'}`}
                         />
                      </svg>
                      <div className="absolute inset-0 flex flex-col items-center justify-center text-center">
                         <div className="text-3xl font-black italic text-[var(--accent-red)] leading-none">5%</div>
                         <div className="text-[10px] font-black uppercase tracking-widest text-[var(--text-muted)] mt-1">VAT Share</div>
                      </div>
                   </div>

                   <div className="space-y-6">
                      <div className="group/item">
                        <div className="text-[10px] font-black uppercase tracking-[0.2em] text-[var(--text-muted)] mb-1">Taxable Net</div>
                        <div className="text-3xl font-black italic text-[var(--text-primary)]">{formatCurrency(netAmount)}</div>
                      </div>
                      <div className="group/item">
                        <div className="text-[10px] font-black uppercase tracking-[0.2em] text-[var(--accent-red)] mb-1">VAT (5% Standard)</div>
                        <div className="text-3xl font-black italic text-[var(--accent-red)]">{formatCurrency(vatAmount)}</div>
                      </div>
                   </div>
                </div>

                <div className="bg-[var(--bg-primary)] border-2 border-[var(--border-subtle)] rounded-3xl p-8 mb-10 relative group/total">
                   <div className="absolute top-0 right-0 w-24 h-24 bg-[var(--accent-yellow)]/5 rounded-full blur-2xl group-hover/total:bg-[var(--accent-yellow)]/10 transition-colors"></div>
                   <div className="flex items-end justify-between relative z-10">
                      <div>
                         <div className="text-[10px] font-black uppercase tracking-[0.2em] text-[var(--text-muted)] mb-2">Total Invoice Amount</div>
                         <div className="text-5xl md:text-6xl font-black italic tracking-tighter text-[var(--text-primary)] leading-none">
                            {formatCurrency(totalAmount).split('.')[0]}<span className="text-2xl opacity-50 font-black">.{formatCurrency(totalAmount).split('.')[1]}</span>
                         </div>
                      </div>
                      <div className="text-[var(--accent-yellow)]">
                         <Calculator className="w-10 h-10 opacity-20" />
                      </div>
                   </div>
                </div>

                <div className="grid sm:grid-cols-2 gap-4">
                   <button
                    onClick={downloadReceipt}
                    className="py-4 bg-[var(--bg-primary)] border-2 border-[var(--border-subtle)] rounded-2xl text-[var(--text-primary)] text-sm font-black uppercase tracking-widest hover:border-[var(--accent-red)] hover:text-[var(--accent-red)] transition-all flex items-center justify-center gap-3 active:scale-95"
                  >
                    <Download className="w-4 h-4" />
                    Save Breakdown
                  </button>
                  <a 
                    href="https://tax.gov.ae/" 
                    target="_blank" 
                    rel="noopener noreferrer"
                    className="py-4 bg-[var(--bg-primary)] border-2 border-[var(--border-subtle)] rounded-2xl text-[var(--text-primary)] text-sm font-black uppercase tracking-widest hover:border-[var(--accent-yellow)] transition-all flex items-center justify-center gap-3 active:scale-95"
                  >
                    <ExternalLink className="w-4 h-4" />
                    FTA Portal
                  </a>
                </div>
              </div>
            ) : (
              <div className="flex-grow flex flex-col items-center justify-center text-center py-20 opacity-30">
                <FileSpreadsheet className="w-32 h-32 text-[var(--text-muted)] mb-6 stroke-[1]" />
                <p className="text-2xl font-black italic uppercase tracking-tighter text-[var(--text-muted)]">
                  Awaiting Input Data<span className="text-[var(--accent-red)]">...</span>
                </p>
              </div>
            )}
          </div>
        </div>
      </div>

      {/* Compliance & Regulatory Reference */}
      <div className="mt-12 grid md:grid-cols-3 gap-6">
         <div className="bg-[var(--bg-card)] border border-[var(--border-subtle)] rounded-[2rem] p-8 hover:border-[var(--accent-red)] transition-all group">
            <div className="w-10 h-10 rounded-xl bg-[var(--accent-red)]/10 text-[var(--accent-red)] flex items-center justify-center mb-6 group-hover:scale-110 transition-transform">
               <Info className="w-5 h-5" />
            </div>
            <h4 className="text-sm font-black uppercase tracking-wider text-[var(--text-primary)] mb-3">Regulatory Basis</h4>
            <p className="text-xs text-[var(--text-secondary)] leading-relaxed font-medium">
               Federal Decree-Law No. (8) of 2017 on Value Added Tax governs all calculations within this system.
            </p>
         </div>
         
         <div className="bg-[var(--bg-card)] border border-[var(--border-subtle)] rounded-[2rem] p-8 hover:border-[var(--accent-yellow)] transition-all group">
            <div className="w-10 h-10 rounded-xl bg-[var(--accent-yellow)]/10 text-[var(--accent-yellow)] flex items-center justify-center mb-6 group-hover:scale-110 transition-transform">
               <ShieldCheck className="w-5 h-5" />
            </div>
            <h4 className="text-sm font-black uppercase tracking-wider text-[var(--text-primary)] mb-3">GCC Compliance</h4>
            <p className="text-xs text-[var(--text-secondary)] leading-relaxed font-medium">
               This tool handles standard-rated supplies (5%) for UAE, maintaining regional standards for GCC financial tools.
            </p>
         </div>

         <div className="bg-[var(--bg-card)] border border-[var(--border-subtle)] rounded-[2rem] p-8 hover:border-[var(--text-primary)] transition-all group">
            <div className="w-10 h-10 rounded-xl bg-[var(--bg-secondary)] text-[var(--text-primary)] flex items-center justify-center mb-6 group-hover:scale-110 transition-transform">
               <FileSpreadsheet className="w-5 h-5" />
            </div>
            <h4 className="text-sm font-black uppercase tracking-wider text-[var(--text-primary)] mb-3">Accounting Exports</h4>
            <p className="text-xs text-[var(--text-secondary)] leading-relaxed font-medium">
               Generated receipts include the "processed" timestamp and specific breakdown required for VAT record-keeping.
            </p>
         </div>
      </div>
    </div>
  );
}

