/**
 * VAT Invoice Template Generator
 * Generates FTA-compliant VAT invoices for UAE businesses
 */
import { useState } from 'react';
import { FileText, Download, Copy, Building2, User, Calendar, DollarSign } from 'lucide-react';

export default function VATInvoiceGenerator() {
  const [invoiceData, setInvoiceData] = useState({
    sellerName: '',
    sellerTRN: '',
    buyerName: '',
    buyerTRN: '',
    invoiceNumber: '',
    invoiceDate: new Date().toISOString().split('T')[0],
    items: [{ description: '', quantity: 1, unitPrice: 0 }],
    vatRate: 5
  });

  const [output, setOutput] = useState('');

  const addItem = () => {
    setInvoiceData({
      ...invoiceData,
      items: [...invoiceData.items, { description: '', quantity: 1, unitPrice: 0 }]
    });
  };

  const updateItem = (index: number, field: string, value: string | number) => {
    const newItems = [...invoiceData.items];
    newItems[index] = { ...newItems[index], [field]: value };
    setInvoiceData({ ...invoiceData, items: newItems });
  };

  const calculateTotals = () => {
    const subtotal = invoiceData.items.reduce((sum, item) => sum + (item.quantity * item.unitPrice), 0);
    const vatAmount = subtotal * (invoiceData.vatRate / 100);
    const total = subtotal + vatAmount;
    return { subtotal, vatAmount, total };
  };

  const generateInvoice = () => {
    const { subtotal, vatAmount, total } = calculateTotals();
    const invoice = `
═══════════════════════════════════════════════════════
                    TAX INVOICE
═══════════════════════════════════════════════════════

SELLER INFORMATION
Company: ${invoiceData.sellerName}
TRN: ${invoiceData.sellerTRN}

BUYER INFORMATION  
Company: ${invoiceData.buyerName}
TRN: ${invoiceData.buyerTRN}

INVOICE DETAILS
Invoice No: ${invoiceData.invoiceNumber}
Date: ${invoiceData.invoiceDate}

───────────────────────────────────────────────────────
ITEMS
───────────────────────────────────────────────────────
${invoiceData.items.map((item, i) => 
  `${i + 1}. ${item.description}
     Qty: ${item.quantity} × AED ${item.unitPrice.toFixed(2)} = AED ${(item.quantity * item.unitPrice).toFixed(2)}`
).join('\n\n')}

───────────────────────────────────────────────────────
TOTALS
───────────────────────────────────────────────────────
Subtotal:        AED ${subtotal.toFixed(2)}
VAT (${invoiceData.vatRate}%):       AED ${vatAmount.toFixed(2)}
═══════════════════════════════════════════════════════
TOTAL:           AED ${total.toFixed(2)}
═══════════════════════════════════════════════════════

This is a tax invoice issued in compliance with UAE VAT Law.
Generated by VDESIGNU SEO Tools Suite
    `;
    setOutput(invoice.trim());
  };

  const copyToClipboard = () => {
    navigator.clipboard.writeText(output);
  };

  return (
    <div className="max-w-6xl mx-auto">
      <div className="grid lg:grid-cols-2 gap-12">
        {/* Input Panel */}
        <div className="bg-[var(--bg-card)] border-2 border-[var(--border-subtle)] rounded-[2.5rem] p-10 shadow-2xl">
          <div className="flex items-center gap-4 mb-10">
            <div className="w-14 h-14 rounded-2xl bg-[var(--accent-red)] flex items-center justify-center text-white shadow-xl">
              <FileText className="w-7 h-7" />
            </div>
            <div>
              <h3 className="text-xl font-black uppercase tracking-tight text-[var(--text-primary)]">VAT Invoice Generator</h3>
              <p className="text-[10px] font-black text-[var(--text-muted)] uppercase tracking-widest">FTA Compliant Template</p>
            </div>
          </div>

          <div className="space-y-6">
            {/* Seller Info */}
            <div className="p-4 bg-[var(--bg-primary)] rounded-2xl border border-[var(--border-subtle)]">
              <div className="flex items-center gap-2 mb-4">
                <Building2 className="w-4 h-4 text-[var(--accent-red)]" />
                <span className="text-[10px] font-black uppercase tracking-widest text-[var(--text-muted)]">Seller Details</span>
              </div>
              <div className="grid grid-cols-2 gap-3">
                <input
                  type="text"
                  placeholder="Company Name"
                  value={invoiceData.sellerName}
                  onChange={(e) => setInvoiceData({...invoiceData, sellerName: e.target.value})}
                  className="px-4 py-3 bg-[var(--bg-card)] border border-[var(--border-subtle)] rounded-xl text-xs"
                />
                <input
                  type="text"
                  placeholder="TRN (Tax Registration Number)"
                  value={invoiceData.sellerTRN}
                  onChange={(e) => setInvoiceData({...invoiceData, sellerTRN: e.target.value})}
                  className="px-4 py-3 bg-[var(--bg-card)] border border-[var(--border-subtle)] rounded-xl text-xs"
                />
              </div>
            </div>

            {/* Buyer Info */}
            <div className="p-4 bg-[var(--bg-primary)] rounded-2xl border border-[var(--border-subtle)]">
              <div className="flex items-center gap-2 mb-4">
                <User className="w-4 h-4 text-[var(--accent-red)]" />
                <span className="text-[10px] font-black uppercase tracking-widest text-[var(--text-muted)]">Buyer Details</span>
              </div>
              <div className="grid grid-cols-2 gap-3">
                <input
                  type="text"
                  placeholder="Company Name"
                  value={invoiceData.buyerName}
                  onChange={(e) => setInvoiceData({...invoiceData, buyerName: e.target.value})}
                  className="px-4 py-3 bg-[var(--bg-card)] border border-[var(--border-subtle)] rounded-xl text-xs"
                />
                <input
                  type="text"
                  placeholder="TRN (Tax Registration Number)"
                  value={invoiceData.buyerTRN}
                  onChange={(e) => setInvoiceData({...invoiceData, buyerTRN: e.target.value})}
                  className="px-4 py-3 bg-[var(--bg-card)] border border-[var(--border-subtle)] rounded-xl text-xs"
                />
              </div>
            </div>

            {/* Invoice Details */}
            <div className="grid grid-cols-2 gap-3">
              <input
                type="text"
                placeholder="Invoice Number"
                value={invoiceData.invoiceNumber}
                onChange={(e) => setInvoiceData({...invoiceData, invoiceNumber: e.target.value})}
                className="px-4 py-3 bg-[var(--bg-primary)] border border-[var(--border-subtle)] rounded-xl text-xs"
              />
              <input
                type="date"
                value={invoiceData.invoiceDate}
                onChange={(e) => setInvoiceData({...invoiceData, invoiceDate: e.target.value})}
                className="px-4 py-3 bg-[var(--bg-primary)] border border-[var(--border-subtle)] rounded-xl text-xs"
              />
            </div>

            {/* Items */}
            <div className="space-y-3">
              <span className="text-[10px] font-black uppercase tracking-widest text-[var(--text-muted)]">Line Items</span>
              {invoiceData.items.map((item, index) => (
                <div key={index} className="grid grid-cols-4 gap-2">
                  <input
                    type="text"
                    placeholder="Description"
                    value={item.description}
                    onChange={(e) => updateItem(index, 'description', e.target.value)}
                    className="col-span-2 px-3 py-2 bg-[var(--bg-primary)] border border-[var(--border-subtle)] rounded-xl text-xs"
                  />
                  <input
                    type="number"
                    placeholder="Qty"
                    value={item.quantity}
                    onChange={(e) => updateItem(index, 'quantity', parseInt(e.target.value) || 0)}
                    className="px-3 py-2 bg-[var(--bg-primary)] border border-[var(--border-subtle)] rounded-xl text-xs"
                  />
                  <input
                    type="number"
                    placeholder="Price"
                    value={item.unitPrice}
                    onChange={(e) => updateItem(index, 'unitPrice', parseFloat(e.target.value) || 0)}
                    className="px-3 py-2 bg-[var(--bg-primary)] border border-[var(--border-subtle)] rounded-xl text-xs"
                  />
                </div>
              ))}
              <button
                onClick={addItem}
                className="w-full py-2 border-2 border-dashed border-[var(--border-subtle)] rounded-xl text-xs font-bold text-[var(--text-muted)] hover:border-[var(--accent-red)] transition-all"
              >
                + Add Line Item
              </button>
            </div>

            <button
              onClick={generateInvoice}
              className="w-full py-4 bg-[var(--accent-red)] text-white font-black uppercase rounded-2xl hover:bg-black transition-all shadow-xl"
            >
              Generate Invoice
            </button>
          </div>
        </div>

        {/* Output Panel */}
        <div className="space-y-8">
          <div className="bg-[var(--bg-card)] border-2 border-[var(--border-subtle)] rounded-[2.5rem] p-8">
            <div className="flex items-center justify-between mb-6">
              <h4 className="text-xs font-black uppercase tracking-widest text-[var(--text-primary)]">Invoice Preview</h4>
              <button
                onClick={copyToClipboard}
                className="flex items-center gap-2 px-4 py-2 bg-[var(--bg-primary)] border border-[var(--border-subtle)] rounded-xl text-[10px] font-bold hover:bg-[var(--accent-red)] hover:text-white transition-all"
              >
                <Copy className="w-3 h-3" /> Copy
              </button>
            </div>
            <pre className="p-6 bg-[var(--bg-primary)] rounded-2xl border border-[var(--border-subtle)] text-xs font-mono text-[var(--text-secondary)] whitespace-pre-wrap overflow-x-auto max-h-[500px]">
              {output || 'Fill in the details above and click Generate Invoice'}
            </pre>
          </div>

          {/* Summary */}
          {output && (
            <div className="bg-[var(--bg-card)] border-2 border-[var(--border-subtle)] rounded-[2.5rem] p-8">
              <h4 className="text-xs font-black uppercase tracking-widest text-[var(--text-primary)] mb-4">Totals</h4>
              <div className="space-y-3">
                <div className="flex justify-between text-sm">
                  <span className="text-[var(--text-muted)]">Subtotal</span>
                  <span className="font-bold text-[var(--text-primary)]">AED {calculateTotals().subtotal.toFixed(2)}</span>
                </div>
                <div className="flex justify-between text-sm">
                  <span className="text-[var(--text-muted)]">VAT ({invoiceData.vatRate}%)</span>
                  <span className="font-bold text-[var(--text-primary)]">AED {calculateTotals().vatAmount.toFixed(2)}</span>
                </div>
                <div className="flex justify-between text-lg pt-3 border-t border-[var(--border-subtle)]">
                  <span className="font-black text-[var(--text-primary)]">Total</span>
                  <span className="font-black text-[var(--accent-red)]">AED {calculateTotals().total.toFixed(2)}</span>
                </div>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
